// Code generated by crafter generator. DO NOT EDIT.

package it

import (
	"crypto/tls"

	cli "github.com/telecom-cloud/client-go/pkg/client"
)

var baseDomain = ""

type ClientSet interface {
	Order() OrderClient
}

type clientSet struct {
	orderCli OrderClient
}

func NewClientSet(baseDomain string, options ...Option) (ClientSet, error) {
	defaultOpt := []Option{
		WithClientOption(cli.WithTLSConfig(&tls.Config{
			InsecureSkipVerify: true,
		})),
	}
	options = append(defaultOpt, options...)
	orderCli, err := NewOrderClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}

	return &clientSet{
		orderCli: orderCli,
	}, nil
}

func (cs *clientSet) Order() OrderClient {
	return cs.orderCli
}
