// Code generated by cft. DO NOT EDIT.

package it

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	order "github.com/telecom-cloud/telecomcloud-sdk-go/service/it/types/order"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type OrderClient interface {
	PlaceOnDemandNewPurchaseOrder(context context.Context, req *order.PlaceOnDemandNewPurchaseOrderRequest, reqOpt ...config.RequestOption) (resp *order.PlaceOnDemandNewPurchaseOrderResponse, rawResponse *protocol.Response, err error)

	PlaceRefundOrder(context context.Context, req *order.PlaceRefundOrderRequest, reqOpt ...config.RequestOption) (resp *order.PlaceRefundOrderResponse, rawResponse *protocol.Response, err error)

	QueryResourceInfoByMasterOrderId(context context.Context, req *order.QueryResourceInfoByMasterOrderIdRequest, reqOpt ...config.RequestOption) (resp *order.QueryResourceInfoByMasterOrderIdResponse, rawResponse *protocol.Response, err error)
}

type orderClient struct {
	client *HttpClient
}

func NewOrderClient(hostUrl string, ops ...Option) (OrderClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &orderClient{
		client: cli,
	}, nil
}

func (s *orderClient) PlaceOnDemandNewPurchaseOrder(ctx context.Context, req *order.PlaceOnDemandNewPurchaseOrderRequest, reqOpt ...config.RequestOption) (resp *order.PlaceOnDemandNewPurchaseOrderResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"Content-Type": "application/x-www-form-urlencoded",
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v3/order/placeOnDemandNewPurchaseOrder")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *orderClient) PlaceRefundOrder(ctx context.Context, req *order.PlaceRefundOrderRequest, reqOpt ...config.RequestOption) (resp *order.PlaceRefundOrderResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"Content-Type": "application/x-www-form-urlencoded",
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v3/order/placeRefundOrder")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *orderClient) QueryResourceInfoByMasterOrderId(ctx context.Context, req *order.QueryResourceInfoByMasterOrderIdRequest, reqOpt ...config.RequestOption) (resp *order.QueryResourceInfoByMasterOrderIdResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v3/order/queryResourceInfoByMasterOrderId")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultOrderClient, _ = NewOrderClient(baseDomain)

func ConfigDefaultOrderClient(ops ...Option) (err error) {
	defaultOrderClient, err = NewOrderClient(baseDomain, ops...)
	return
}

func PlaceOnDemandNewPurchaseOrder(context context.Context, req *order.PlaceOnDemandNewPurchaseOrderRequest, reqOpt ...config.RequestOption) (resp *order.PlaceOnDemandNewPurchaseOrderResponse, rawResponse *protocol.Response, err error) {
	return defaultOrderClient.PlaceOnDemandNewPurchaseOrder(context, req, reqOpt...)
}

func PlaceRefundOrder(context context.Context, req *order.PlaceRefundOrderRequest, reqOpt ...config.RequestOption) (resp *order.PlaceRefundOrderResponse, rawResponse *protocol.Response, err error) {
	return defaultOrderClient.PlaceRefundOrder(context, req, reqOpt...)
}

func QueryResourceInfoByMasterOrderId(context context.Context, req *order.QueryResourceInfoByMasterOrderIdRequest, reqOpt ...config.RequestOption) (resp *order.QueryResourceInfoByMasterOrderIdResponse, rawResponse *protocol.Response, err error) {
	return defaultOrderClient.QueryResourceInfoByMasterOrderId(context, req, reqOpt...)
}
