// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package it

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	sales "github.com/telecom-cloud/telecomcloud-sdk-go/service/it/types/sales"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type SalesEntryClient interface {
	DescribeSalesEntry(context context.Context, req *sales.DescribeSalesEntryRequest, reqOpt ...config.RequestOption) (resp *sales.DescribeSalesEntryResponse, rawResponse *protocol.Response, err error)
}

type salesEntryClient struct {
	client *HttpClient
}

func NewSalesEntryClient(hostUrl string, ops ...Option) (SalesEntryClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &salesEntryClient{
		client: cli,
	}, nil
}

func (s *salesEntryClient) DescribeSalesEntry(ctx context.Context, req *sales.DescribeSalesEntryRequest, reqOpt ...config.RequestOption) (resp *sales.DescribeSalesEntryResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"pageSize":     req.GetPageSize(),
		"pageNum":      req.GetPageNum(),
		"serviceTag":   req.GetServiceTag(),
		"resourceType": req.GetResourceType(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/api/mdse/offers/pagebyserviceresource")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultSalesEntryClient, _ = NewSalesEntryClient(baseDomain)

func ConfigDefaultSalesEntryClient(ops ...Option) (err error) {
	defaultSalesEntryClient, err = NewSalesEntryClient(baseDomain, ops...)
	return
}

func DescribeSalesEntry(context context.Context, req *sales.DescribeSalesEntryRequest, reqOpt ...config.RequestOption) (resp *sales.DescribeSalesEntryResponse, rawResponse *protocol.Response, err error) {
	return defaultSalesEntryClient.DescribeSalesEntry(context, req, reqOpt...)
}
