// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package redis

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	account "github.com/telecom-cloud/telecomcloud-sdk-go/service/redis/types/account"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type AccountClient interface {
	CreateAccount(context context.Context, req *account.CreateAccountRequest, reqOpt ...config.RequestOption) (resp *account.CreateAccountResponse, rawResponse *protocol.Response, err error)

	DescribeAccount(context context.Context, req *account.DescribeAccountRequest, reqOpt ...config.RequestOption) (resp *account.DescribeAccountResponse, rawResponse *protocol.Response, err error)
}

type accountClient struct {
	client *HttpClient
}

func NewAccountClient(hostUrl string, ops ...Option) (AccountClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &accountClient{
		client: cli,
	}, nil
}

func (s *accountClient) CreateAccount(ctx context.Context, req *account.CreateAccountRequest, reqOpt ...config.RequestOption) (resp *account.CreateAccountResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v2/userMgr/createAccount")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *accountClient) DescribeAccount(ctx context.Context, req *account.DescribeAccountRequest, reqOpt ...config.RequestOption) (resp *account.DescribeAccountResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"prodInstId": req.GetProdInstId(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v2/userMgr/describeAccounts")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultAccountClient, _ = NewAccountClient(baseDomain)

func ConfigDefaultAccountClient(ops ...Option) (err error) {
	defaultAccountClient, err = NewAccountClient(baseDomain, ops...)
	return
}

func CreateAccount(context context.Context, req *account.CreateAccountRequest, reqOpt ...config.RequestOption) (resp *account.CreateAccountResponse, rawResponse *protocol.Response, err error) {
	return defaultAccountClient.CreateAccount(context, req, reqOpt...)
}

func DescribeAccount(context context.Context, req *account.DescribeAccountRequest, reqOpt ...config.RequestOption) (resp *account.DescribeAccountResponse, rawResponse *protocol.Response, err error) {
	return defaultAccountClient.DescribeAccount(context, req, reqOpt...)
}
