// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package redis

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	instance "github.com/telecom-cloud/telecomcloud-sdk-go/service/redis/types/instance"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type InstanceClient interface {
	DescribeInstances(context context.Context, req *instance.DescribeInstancesRequest, reqOpt ...config.RequestOption) (resp *instance.DescribeInstancesResponse, rawResponse *protocol.Response, err error)
}

type instanceClient struct {
	client *HttpClient
}

func NewInstanceClient(hostUrl string, ops ...Option) (InstanceClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &instanceClient{
		client: cli,
	}, nil
}

func (s *instanceClient) DescribeInstances(ctx context.Context, req *instance.DescribeInstancesRequest, reqOpt ...config.RequestOption) (resp *instance.DescribeInstancesResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"pageIndex":    req.GetPageIndex(),
		"pageSize":     req.GetPageSize(),
		"instanceName": req.GetInstanceName(),
		"labelIds":     req.GetLabelIds(),
		"projectId":    req.GetProjectId(),
		"queryDeleted": req.GetQueryDeleted(),
		"queryLabel":   req.GetQueryLabel(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v2/instanceManageMgrServant/describeInstances")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultInstanceClient, _ = NewInstanceClient(baseDomain)

func ConfigDefaultInstanceClient(ops ...Option) (err error) {
	defaultInstanceClient, err = NewInstanceClient(baseDomain, ops...)
	return
}

func DescribeInstances(context context.Context, req *instance.DescribeInstancesRequest, reqOpt ...config.RequestOption) (resp *instance.DescribeInstancesResponse, rawResponse *protocol.Response, err error) {
	return defaultInstanceClient.DescribeInstances(context, req, reqOpt...)
}
