// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package cloudaudit

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	manager "github.com/telecom-cloud/telecomcloud-sdk-go/service/cloudaudit/types/manager"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type ManagerClient interface {
	CheckServiceStatus(context context.Context, req *manager.ManagerServiceRequest, reqOpt ...config.RequestOption) (resp *manager.CheckServiceStatusResponse, rawResponse *protocol.Response, err error)

	OpenService(context context.Context, req *manager.ManagerServiceRequest, reqOpt ...config.RequestOption) (resp *manager.OpenServiceResponse, rawResponse *protocol.Response, err error)
}

type managerClient struct {
	client *HttpClient
}

func NewManagerClient(hostUrl string, ops ...Option) (ManagerClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &managerClient{
		client: cli,
	}, nil
}

func (s *managerClient) CheckServiceStatus(ctx context.Context, req *manager.ManagerServiceRequest, reqOpt ...config.RequestOption) (resp *manager.CheckServiceStatusResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionid":  req.GetRegionId(),
			"accountid": req.GetAccountId(),
			"userid":    req.GetUserId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v2/manager/user/enable")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *managerClient) OpenService(ctx context.Context, req *manager.ManagerServiceRequest, reqOpt ...config.RequestOption) (resp *manager.OpenServiceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionid":  req.GetRegionId(),
			"accountid": req.GetAccountId(),
			"userid":    req.GetUserId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v2/manager/user")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultManagerClient, _ = NewManagerClient(baseDomain)

func ConfigDefaultManagerClient(ops ...Option) (err error) {
	defaultManagerClient, err = NewManagerClient(baseDomain, ops...)
	return
}

func CheckServiceStatus(context context.Context, req *manager.ManagerServiceRequest, reqOpt ...config.RequestOption) (resp *manager.CheckServiceStatusResponse, rawResponse *protocol.Response, err error) {
	return defaultManagerClient.CheckServiceStatus(context, req, reqOpt...)
}

func OpenService(context context.Context, req *manager.ManagerServiceRequest, reqOpt ...config.RequestOption) (resp *manager.OpenServiceResponse, rawResponse *protocol.Response, err error) {
	return defaultManagerClient.OpenService(context, req, reqOpt...)
}
