// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package ebs

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	ebs "github.com/telecom-cloud/telecomcloud-sdk-go/service/ebs/types/ebs"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type EbsClient interface {
	GetEbsInfo(context context.Context, req *ebs.GetEbsInfoRequest, reqOpt ...config.RequestOption) (resp *ebs.GetEbsInfoResponse, rawResponse *protocol.Response, err error)
}

type ebsClient struct {
	client *HttpClient
}

func NewEbsClient(hostUrl string, ops ...Option) (EbsClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &ebsClient{
		client: cli,
	}, nil
}

func (s *ebsClient) GetEbsInfo(ctx context.Context, req *ebs.GetEbsInfoRequest, reqOpt ...config.RequestOption) (resp *ebs.GetEbsInfoResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"regionID": req.GetRegionId(),
		"diskID":   req.GetDiskId(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v4/ebs/info-ebs")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultEbsClient, _ = NewEbsClient(baseDomain)

func ConfigDefaultEbsClient(ops ...Option) (err error) {
	defaultEbsClient, err = NewEbsClient(baseDomain, ops...)
	return
}

func GetEbsInfo(context context.Context, req *ebs.GetEbsInfoRequest, reqOpt ...config.RequestOption) (resp *ebs.GetEbsInfoResponse, rawResponse *protocol.Response, err error) {
	return defaultEbsClient.GetEbsInfo(context, req, reqOpt...)
}
