// Code generated by cft. DO NOT EDIT.

package eci

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	flavor "github.com/telecom-cloud/telecomcloud-sdk-go/service/eci/types/flavor"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type FlavorClient interface {
	DescribeAvailableResource(context context.Context, req *flavor.DescribeAvailableResourceRequest, reqOpt ...config.RequestOption) (resp *flavor.DescribeAvailableResourceResponse, rawResponse *protocol.Response, err error)
}

type flavorClient struct {
	client *HttpClient
}

func NewFlavorClient(hostUrl string, ops ...Option) (FlavorClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &flavorClient{
		client: cli,
	}, nil
}

func (s *flavorClient) DescribeAvailableResource(ctx context.Context, req *flavor.DescribeAvailableResourceRequest, reqOpt ...config.RequestOption) (resp *flavor.DescribeAvailableResourceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/eci/api/v1/flavor/describeAvailableResource")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultFlavorClient, _ = NewFlavorClient(baseDomain)

func ConfigDefaultFlavorClient(ops ...Option) (err error) {
	defaultFlavorClient, err = NewFlavorClient(baseDomain, ops...)
	return
}

func DescribeAvailableResource(context context.Context, req *flavor.DescribeAvailableResourceRequest, reqOpt ...config.RequestOption) (resp *flavor.DescribeAvailableResourceResponse, rawResponse *protocol.Response, err error) {
	return defaultFlavorClient.DescribeAvailableResource(context, req, reqOpt...)
}
