// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package eci

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	flavor "github.com/telecom-cloud/telecomcloud-sdk-go/service/eci/types/flavor"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type FlavorClient interface {
	DescribeAvailableResource(context context.Context, req *flavor.DescribeAvailableResourceRequest, reqOpt ...config.RequestOption) (resp *flavor.DescribeAvailableResourceResponse, rawResponse *protocol.Response, err error)
}

type flavorClient struct {
	client *HttpClient
}

func NewFlavorClient(hostUrl string, ops ...Option) (FlavorClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &flavorClient{
		client: cli,
	}, nil
}

func (s *flavorClient) DescribeAvailableResource(ctx context.Context, req *flavor.DescribeAvailableResourceRequest, reqOpt ...config.RequestOption) (resp *flavor.DescribeAvailableResourceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/eci/api/v1/containers/describeAvailableResource")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultFlavorClient, _ = NewFlavorClient(baseDomain)

func ConfigDefaultFlavorClient(ops ...Option) (err error) {
	defaultFlavorClient, err = NewFlavorClient(baseDomain, ops...)
	return
}

func DescribeAvailableResource(context context.Context, req *flavor.DescribeAvailableResourceRequest, reqOpt ...config.RequestOption) (resp *flavor.DescribeAvailableResourceResponse, rawResponse *protocol.Response, err error) {
	return defaultFlavorClient.DescribeAvailableResource(context, req, reqOpt...)
}
