// Code generated by cft. DO NOT EDIT.

package eci

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	imagecache "github.com/telecom-cloud/telecomcloud-sdk-go/service/eci/types/imagecache"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type ImageCacheClient interface {
	CreateImageCache(context context.Context, req *imagecache.CreateImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.CreateImageCacheResponse, rawResponse *protocol.Response, err error)

	DeleteImageCache(context context.Context, req *imagecache.DeleteImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.DeleteImageCacheResponse, rawResponse *protocol.Response, err error)

	DescribeImageCache(context context.Context, req *imagecache.DescribeImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.DescribeImageCacheResponse, rawResponse *protocol.Response, err error)

	GetImageCache(context context.Context, req *imagecache.GetImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.GetImageCacheResponse, rawResponse *protocol.Response, err error)
}

type imageCacheClient struct {
	client *HttpClient
}

func NewImageCacheClient(hostUrl string, ops ...Option) (ImageCacheClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &imageCacheClient{
		client: cli,
	}, nil
}

func (s *imageCacheClient) CreateImageCache(ctx context.Context, req *imagecache.CreateImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.CreateImageCacheResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/eci/api/v1/imageCache/createImageCache")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *imageCacheClient) DeleteImageCache(ctx context.Context, req *imagecache.DeleteImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.DeleteImageCacheResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"imageCacheId": req.GetImageCacheId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodDelete, "/eci/api/v1/imageCache/deleteImageCache/{imageCacheId}")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *imageCacheClient) DescribeImageCache(ctx context.Context, req *imagecache.DescribeImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.DescribeImageCacheResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/eci/api/v1/imageCache/describeImageCaches")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *imageCacheClient) GetImageCache(ctx context.Context, req *imagecache.GetImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.GetImageCacheResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"imageCacheId": req.GetImageCacheId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/eci/api/v1/imageCache//deleteImageCache/{imageCacheId}")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultImageCacheClient, _ = NewImageCacheClient(baseDomain)

func ConfigDefaultImageCacheClient(ops ...Option) (err error) {
	defaultImageCacheClient, err = NewImageCacheClient(baseDomain, ops...)
	return
}

func CreateImageCache(context context.Context, req *imagecache.CreateImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.CreateImageCacheResponse, rawResponse *protocol.Response, err error) {
	return defaultImageCacheClient.CreateImageCache(context, req, reqOpt...)
}

func DeleteImageCache(context context.Context, req *imagecache.DeleteImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.DeleteImageCacheResponse, rawResponse *protocol.Response, err error) {
	return defaultImageCacheClient.DeleteImageCache(context, req, reqOpt...)
}

func DescribeImageCache(context context.Context, req *imagecache.DescribeImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.DescribeImageCacheResponse, rawResponse *protocol.Response, err error) {
	return defaultImageCacheClient.DescribeImageCache(context, req, reqOpt...)
}

func GetImageCache(context context.Context, req *imagecache.GetImageCacheRequest, reqOpt ...config.RequestOption) (resp *imagecache.GetImageCacheResponse, rawResponse *protocol.Response, err error) {
	return defaultImageCacheClient.GetImageCache(context, req, reqOpt...)
}
