// Code generated by cft. DO NOT EDIT.

package eci

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	region "github.com/telecom-cloud/telecomcloud-sdk-go/service/eci/types/region"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type RegionClient interface {
	DescribeRegion(context context.Context, req *region.DescribeRegionRequest, reqOpt ...config.RequestOption) (resp *region.DescribeRegionResponse, rawResponse *protocol.Response, err error)
}

type regionClient struct {
	client *HttpClient
}

func NewRegionClient(hostUrl string, ops ...Option) (RegionClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &regionClient{
		client: cli,
	}, nil
}

func (s *regionClient) DescribeRegion(ctx context.Context, req *region.DescribeRegionRequest, reqOpt ...config.RequestOption) (resp *region.DescribeRegionResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/eci/api/v1/region")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultRegionClient, _ = NewRegionClient(baseDomain)

func ConfigDefaultRegionClient(ops ...Option) (err error) {
	defaultRegionClient, err = NewRegionClient(baseDomain, ops...)
	return
}

func DescribeRegion(context context.Context, req *region.DescribeRegionRequest, reqOpt ...config.RequestOption) (resp *region.DescribeRegionResponse, rawResponse *protocol.Response, err error) {
	return defaultRegionClient.DescribeRegion(context, req, reqOpt...)
}
