// Code generated by crafter generator. DO NOT EDIT.

package ecs

import (
	"crypto/tls"

	cli "github.com/telecom-cloud/client-go/pkg/client"
)

var baseDomain = "https://ecs-global.ctapi.ctyun.cn"

type ClientSet interface {
	Ecs() EcsClient
	Region() RegionClient
}

type clientSet struct {
	ecsCli    EcsClient
	regionCli RegionClient
}

func NewClientSet(baseDomain string, options ...Option) (ClientSet, error) {
	defaultOpt := []Option{
		WithClientOption(cli.WithTLSConfig(&tls.Config{
			InsecureSkipVerify: true,
		})),
	}
	options = append(defaultOpt, options...)
	ecsCli, err := NewEcsClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}
	regionCli, err := NewRegionClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}

	return &clientSet{
		ecsCli:    ecsCli,
		regionCli: regionCli,
	}, nil
}

func (cs *clientSet) Ecs() EcsClient {
	return cs.ecsCli
}

func (cs *clientSet) Region() RegionClient {
	return cs.regionCli
}
