// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package ecs

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	ecs "github.com/telecom-cloud/telecomcloud-sdk-go/service/ecs/types/ecs"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type EcsClient interface {
	CreateInstance(context context.Context, req *ecs.CreateInstanceRequest, reqOpt ...config.RequestOption) (resp *ecs.CreateInstanceResponse, rawResponse *protocol.Response, err error)

	ListInstance(context context.Context, req *ecs.ListInstanceRequest, reqOpt ...config.RequestOption) (resp *ecs.ListInstanceResponse, rawResponse *protocol.Response, err error)
}

type ecsClient struct {
	client *HttpClient
}

func NewEcsClient(hostUrl string, ops ...Option) (EcsClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &ecsClient{
		client: cli,
	}, nil
}

func (s *ecsClient) CreateInstance(ctx context.Context, req *ecs.CreateInstanceRequest, reqOpt ...config.RequestOption) (resp *ecs.CreateInstanceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/ecs/create-instance")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *ecsClient) ListInstance(ctx context.Context, req *ecs.ListInstanceRequest, reqOpt ...config.RequestOption) (resp *ecs.ListInstanceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/ecs/list-instances")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultEcsClient, _ = NewEcsClient(baseDomain)

func ConfigDefaultEcsClient(ops ...Option) (err error) {
	defaultEcsClient, err = NewEcsClient(baseDomain, ops...)
	return
}

func CreateInstance(context context.Context, req *ecs.CreateInstanceRequest, reqOpt ...config.RequestOption) (resp *ecs.CreateInstanceResponse, rawResponse *protocol.Response, err error) {
	return defaultEcsClient.CreateInstance(context, req, reqOpt...)
}

func ListInstance(context context.Context, req *ecs.ListInstanceRequest, reqOpt ...config.RequestOption) (resp *ecs.ListInstanceResponse, rawResponse *protocol.Response, err error) {
	return defaultEcsClient.ListInstance(context, req, reqOpt...)
}
