// Code generated by cft. DO NOT EDIT.

package ecs

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	region "github.com/telecom-cloud/telecomcloud-sdk-go/service/ecs/types/region"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type RegionClient interface {
	GetZones(context context.Context, req *region.GetZonesRequest, reqOpt ...config.RequestOption) (resp *region.GetZonesResponse, rawResponse *protocol.Response, err error)
}

type regionClient struct {
	client *HttpClient
}

func NewRegionClient(hostUrl string, ops ...Option) (RegionClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &regionClient{
		client: cli,
	}, nil
}

func (s *regionClient) GetZones(ctx context.Context, req *region.GetZonesRequest, reqOpt ...config.RequestOption) (resp *region.GetZonesResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(map[string]interface{}{
			"regionID": req.GetRegionID(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/region/get-zones")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultRegionClient, _ = NewRegionClient(baseDomain)

func ConfigDefaultRegionClient(ops ...Option) (err error) {
	defaultRegionClient, err = NewRegionClient(baseDomain, ops...)
	return
}

func GetZones(context context.Context, req *region.GetZonesRequest, reqOpt ...config.RequestOption) (resp *region.GetZonesResponse, rawResponse *protocol.Response, err error) {
	return defaultRegionClient.GetZones(context, req, reqOpt...)
}
