// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package hpfs

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	hpfs "github.com/telecom-cloud/telecomcloud-sdk-go/service/hpfs/types/hpfs"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type HpfsClient interface {
	ListSfs(context context.Context, req *hpfs.ListSfsRequest, reqOpt ...config.RequestOption) (resp *hpfs.ListSfsResponse, rawResponse *protocol.Response, err error)
}

type hpfsClient struct {
	client *HttpClient
}

func NewHpfsClient(hostUrl string, ops ...Option) (HpfsClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &hpfsClient{
		client: cli,
	}, nil
}

func (s *hpfsClient) ListSfs(ctx context.Context, req *hpfs.ListSfsRequest, reqOpt ...config.RequestOption) (resp *hpfs.ListSfsResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"regionID":    req.GetRegionID(),
		"sfsStatus":   req.GetSfsStatus(),
		"sfsProtocol": req.GetSfsProtocol(),
		"azName":      req.GetAzName(),
		"projectID":   req.GetProjectID(),
		"pageSize":    req.GetPageSize(),
		"pageNo":      req.GetPageNo(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v4/hpfs/list-sfs")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultHpfsClient, _ = NewHpfsClient(baseDomain)

func ConfigDefaultHpfsClient(ops ...Option) (err error) {
	defaultHpfsClient, err = NewHpfsClient(baseDomain, ops...)
	return
}

func ListSfs(context context.Context, req *hpfs.ListSfsRequest, reqOpt ...config.RequestOption) (resp *hpfs.ListSfsResponse, rawResponse *protocol.Response, err error) {
	return defaultHpfsClient.ListSfs(context, req, reqOpt...)
}
