// Code generated by crafter generator. DO NOT EDIT.

package vpce

import (
	"crypto/tls"

	cli "github.com/telecom-cloud/client-go/pkg/client"
)

var baseDomain = "https://ct-global.ctapi.ctyun.cn"

type ClientSet interface {
	VpcEndpoint() VpcEndpointClient
}

type clientSet struct {
	vpcEndpointCli VpcEndpointClient
}

func NewClientSet(baseDomain string, options ...Option) (ClientSet, error) {
	defaultOpt := []Option{
		WithClientOption(cli.WithTLSConfig(&tls.Config{
			InsecureSkipVerify: true,
		})),
	}
	options = append(defaultOpt, options...)
	vpcEndpointCli, err := NewVpcEndpointClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}

	return &clientSet{
		vpcEndpointCli: vpcEndpointCli,
	}, nil
}

func (cs *clientSet) VpcEndpoint() VpcEndpointClient {
	return cs.vpcEndpointCli
}
