// Code generated by cft. DO NOT EDIT.

package vpce

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	vpce "github.com/telecom-cloud/telecomcloud-sdk-go/service/vpce/types/vpce"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type VpcEndpointClient interface {
	CreateEndpoint(context context.Context, req *vpce.CreateEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.CreateEndpointResponse, rawResponse *protocol.Response, err error)

	DeleteEndpoint(context context.Context, req *vpce.DeleteEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.DeleteEndpointResponse, rawResponse *protocol.Response, err error)

	GetEndpoint(context context.Context, req *vpce.DeleteEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.GetEndpointResponse, rawResponse *protocol.Response, err error)

	CreateEndpointWhitelist(context context.Context, req *vpce.CreateEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.CreateEndpointWhitelistResponse, rawResponse *protocol.Response, err error)

	DeleteEndpointWhitelist(context context.Context, req *vpce.DeleteEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.DeleteEndpointWhitelistResponse, rawResponse *protocol.Response, err error)

	ListEndpointWhitelist(context context.Context, req *vpce.ListEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.ListEndpointWhitelistResponse, rawResponse *protocol.Response, err error)
}

type vpcEndpointClient struct {
	client *HttpClient
}

func NewVpcEndpointClient(hostUrl string, ops ...Option) (VpcEndpointClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &vpcEndpointClient{
		client: cli,
	}, nil
}

func (s *vpcEndpointClient) CreateEndpoint(ctx context.Context, req *vpce.CreateEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.CreateEndpointResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/paas/vpce/create-endpoint")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *vpcEndpointClient) DeleteEndpoint(ctx context.Context, req *vpce.DeleteEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.DeleteEndpointResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodDelete, "/v4/paas/vpce/delete-endpoint")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *vpcEndpointClient) GetEndpoint(ctx context.Context, req *vpce.DeleteEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.GetEndpointResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v4/paas/vpce/show-endpoint")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *vpcEndpointClient) CreateEndpointWhitelist(ctx context.Context, req *vpce.CreateEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.CreateEndpointWhitelistResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/vpce/create-endpoint-service-whitelist")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *vpcEndpointClient) DeleteEndpointWhitelist(ctx context.Context, req *vpce.DeleteEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.DeleteEndpointWhitelistResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/vpce/delete-endpoint-service-whitelist")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *vpcEndpointClient) ListEndpointWhitelist(ctx context.Context, req *vpce.ListEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.ListEndpointWhitelistResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.OpenapiResponse{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(map[string]interface{}{
			"regionId":          req.GetRegionID(),
			"endpointServiceID": req.GetEndpointServiceID(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/vpce/list-endpoint-service-whitelist")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultVpcEndpointClient, _ = NewVpcEndpointClient(baseDomain)

func ConfigDefaultVpcEndpointClient(ops ...Option) (err error) {
	defaultVpcEndpointClient, err = NewVpcEndpointClient(baseDomain, ops...)
	return
}

func CreateEndpoint(context context.Context, req *vpce.CreateEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.CreateEndpointResponse, rawResponse *protocol.Response, err error) {
	return defaultVpcEndpointClient.CreateEndpoint(context, req, reqOpt...)
}

func DeleteEndpoint(context context.Context, req *vpce.DeleteEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.DeleteEndpointResponse, rawResponse *protocol.Response, err error) {
	return defaultVpcEndpointClient.DeleteEndpoint(context, req, reqOpt...)
}

func GetEndpoint(context context.Context, req *vpce.DeleteEndpointRequest, reqOpt ...config.RequestOption) (resp *vpce.GetEndpointResponse, rawResponse *protocol.Response, err error) {
	return defaultVpcEndpointClient.GetEndpoint(context, req, reqOpt...)
}

func CreateEndpointWhitelist(context context.Context, req *vpce.CreateEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.CreateEndpointWhitelistResponse, rawResponse *protocol.Response, err error) {
	return defaultVpcEndpointClient.CreateEndpointWhitelist(context, req, reqOpt...)
}

func DeleteEndpointWhitelist(context context.Context, req *vpce.DeleteEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.DeleteEndpointWhitelistResponse, rawResponse *protocol.Response, err error) {
	return defaultVpcEndpointClient.DeleteEndpointWhitelist(context, req, reqOpt...)
}

func ListEndpointWhitelist(context context.Context, req *vpce.ListEndpointWhitelistRequest, reqOpt ...config.RequestOption) (resp *vpce.ListEndpointWhitelistResponse, rawResponse *protocol.Response, err error) {
	return defaultVpcEndpointClient.ListEndpointWhitelist(context, req, reqOpt...)
}
