// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package crs

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	artifact "github.com/telecom-cloud/telecomcloud-sdk-go/service/crs/types/artifact"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type ArtifactClient interface {
	ListArtifact(context context.Context, req *artifact.ListArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.ListArtifactResponse, rawResponse *protocol.Response, err error)

	GetArtifact(context context.Context, req *artifact.GetArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.GetArtifactResponse, rawResponse *protocol.Response, err error)

	DeleteArtifact(context context.Context, req *artifact.DeleteArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.DeleteArtifactResponse, rawResponse *protocol.Response, err error)
}

type artifactClient struct {
	client *HttpClient
}

func NewArtifactClient(hostUrl string, ops ...Option) (ArtifactClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &artifactClient{
		client: cli,
	}, nil
}

func (s *artifactClient) ListArtifact(ctx context.Context, req *artifact.ListArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.ListArtifactResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(map[string]interface{}{
			"instanceId":   req.GetInstanceId(),
			"repositoryId": req.GetRepositoryId(),
			"pageNum":      req.GetPageNum(),
			"pageSize":     req.GetPageSize(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/listArtifact")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *artifactClient) GetArtifact(ctx context.Context, req *artifact.GetArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.GetArtifactResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(map[string]interface{}{
			"instanceId":   req.GetInstanceId(),
			"repositoryId": req.GetRepositoryId(),
			"reference":    req.GetReference(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/getArtifact")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *artifactClient) DeleteArtifact(ctx context.Context, req *artifact.DeleteArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.DeleteArtifactResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(map[string]interface{}{
			"instanceId":   req.GetInstanceId(),
			"repositoryId": req.GetRepositoryId(),
			"reference":    req.GetReference(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/deleteArtifact")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultArtifactClient, _ = NewArtifactClient(baseDomain)

func ConfigDefaultArtifactClient(ops ...Option) (err error) {
	defaultArtifactClient, err = NewArtifactClient(baseDomain, ops...)
	return
}

func ListArtifact(context context.Context, req *artifact.ListArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.ListArtifactResponse, rawResponse *protocol.Response, err error) {
	return defaultArtifactClient.ListArtifact(context, req, reqOpt...)
}

func GetArtifact(context context.Context, req *artifact.GetArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.GetArtifactResponse, rawResponse *protocol.Response, err error) {
	return defaultArtifactClient.GetArtifact(context, req, reqOpt...)
}

func DeleteArtifact(context context.Context, req *artifact.DeleteArtifactRequest, reqOpt ...config.RequestOption) (resp *artifact.DeleteArtifactResponse, rawResponse *protocol.Response, err error) {
	return defaultArtifactClient.DeleteArtifact(context, req, reqOpt...)
}
