// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package crs

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	repositorysync "github.com/telecom-cloud/telecomcloud-sdk-go/service/crs/types/repositorysync"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type RepositorySyncTaskClient interface {
	CreateRepositorySyncTask(context context.Context, req *repositorysync.CreateRepositorySyncTaskRequest, reqOpt ...config.RequestOption) (resp *repositorysync.CreateRepositorySyncTaskResponse, rawResponse *protocol.Response, err error)

	GetRepositorySyncTask(context context.Context, req *repositorysync.GetRepositorySyncTaskRequest, reqOpt ...config.RequestOption) (resp *repositorysync.GetRepositorySyncTaskResponse, rawResponse *protocol.Response, err error)
}

type repositorySyncTaskClient struct {
	client *HttpClient
}

func NewRepositorySyncTaskClient(hostUrl string, ops ...Option) (RepositorySyncTaskClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &repositorySyncTaskClient{
		client: cli,
	}, nil
}

func (s *repositorySyncTaskClient) CreateRepositorySyncTask(ctx context.Context, req *repositorysync.CreateRepositorySyncTaskRequest, reqOpt ...config.RequestOption) (resp *repositorysync.CreateRepositorySyncTaskResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v2/createRepoSyncTask")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *repositorySyncTaskClient) GetRepositorySyncTask(ctx context.Context, req *repositorysync.GetRepositorySyncTaskRequest, reqOpt ...config.RequestOption) (resp *repositorysync.GetRepositorySyncTaskResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"taskId": req.GetTaskId(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v2/getRepoSyncTask")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultRepositorySyncTaskClient, _ = NewRepositorySyncTaskClient(baseDomain)

func ConfigDefaultRepositorySyncTaskClient(ops ...Option) (err error) {
	defaultRepositorySyncTaskClient, err = NewRepositorySyncTaskClient(baseDomain, ops...)
	return
}

func CreateRepositorySyncTask(context context.Context, req *repositorysync.CreateRepositorySyncTaskRequest, reqOpt ...config.RequestOption) (resp *repositorysync.CreateRepositorySyncTaskResponse, rawResponse *protocol.Response, err error) {
	return defaultRepositorySyncTaskClient.CreateRepositorySyncTask(context, req, reqOpt...)
}

func GetRepositorySyncTask(context context.Context, req *repositorysync.GetRepositorySyncTaskRequest, reqOpt ...config.RequestOption) (resp *repositorysync.GetRepositorySyncTaskResponse, rawResponse *protocol.Response, err error) {
	return defaultRepositorySyncTaskClient.GetRepositorySyncTask(context, req, reqOpt...)
}
