// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package isuite

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	gateway "github.com/telecom-cloud/telecomcloud-sdk-go/service/isuite/gateway"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type GatewayClient interface {
	CreateGateway(context context.Context, req *gateway.CreateGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.CreateGatewayResponse, rawResponse *protocol.Response, err error)

	DeleteGateway(context context.Context, req *gateway.DeleteGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.DeleteGatewayResponse, rawResponse *protocol.Response, err error)

	UpdateGateway(context context.Context, req *gateway.UpdateGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.UpdateGatewayResponse, rawResponse *protocol.Response, err error)

	GetGateway(context context.Context, req *gateway.GetGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.GetGatewayResponse, rawResponse *protocol.Response, err error)

	ListGateway(context context.Context, req *gateway.ListGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.ListGatewayResponse, rawResponse *protocol.Response, err error)
}

type gatewayClient struct {
	client *HttpClient
}

func NewGatewayClient(hostUrl string, ops ...Option) (GatewayClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &gatewayClient{
		client: cli,
	}, nil
}

func (s *gatewayClient) CreateGateway(ctx context.Context, req *gateway.CreateGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.CreateGatewayResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/isuite/api/v1/gateways")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *gatewayClient) DeleteGateway(ctx context.Context, req *gateway.DeleteGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.DeleteGatewayResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"gatewayId": req.GetGatewayId(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodDelete, "/isuite/api/v1/gateways/:gatewayId")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *gatewayClient) UpdateGateway(ctx context.Context, req *gateway.UpdateGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.UpdateGatewayResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"gatewayId": req.GetGatewayId(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPut, "/isuite/api/v1/gateways/:gatewayId")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *gatewayClient) GetGateway(ctx context.Context, req *gateway.GetGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.GetGatewayResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"gatewayId": req.GetGatewayId(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/isuite/api/v1/gateways/:gatewayId")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *gatewayClient) ListGateway(ctx context.Context, req *gateway.ListGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.ListGatewayResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"clusterId": req.GetClusterId(),
		"name":      req.GetName(),
		"namespace": req.GetNamespace(),
		"status":    req.GetStatus(),
		"pageNum":   req.GetPageNum(),
		"pageSize":  req.GetPageSize(),
		"sortBy":    req.GetSortBy(),
		"order":     req.GetOrder(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/isuite/api/v1/gateways")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultGatewayClient, _ = NewGatewayClient(baseDomain)

func ConfigDefaultGatewayClient(ops ...Option) (err error) {
	defaultGatewayClient, err = NewGatewayClient(baseDomain, ops...)
	return
}

func CreateGateway(context context.Context, req *gateway.CreateGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.CreateGatewayResponse, rawResponse *protocol.Response, err error) {
	return defaultGatewayClient.CreateGateway(context, req, reqOpt...)
}

func DeleteGateway(context context.Context, req *gateway.DeleteGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.DeleteGatewayResponse, rawResponse *protocol.Response, err error) {
	return defaultGatewayClient.DeleteGateway(context, req, reqOpt...)
}

func UpdateGateway(context context.Context, req *gateway.UpdateGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.UpdateGatewayResponse, rawResponse *protocol.Response, err error) {
	return defaultGatewayClient.UpdateGateway(context, req, reqOpt...)
}

func GetGateway(context context.Context, req *gateway.GetGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.GetGatewayResponse, rawResponse *protocol.Response, err error) {
	return defaultGatewayClient.GetGateway(context, req, reqOpt...)
}

func ListGateway(context context.Context, req *gateway.ListGatewayRequest, reqOpt ...config.RequestOption) (resp *gateway.ListGatewayResponse, rawResponse *protocol.Response, err error) {
	return defaultGatewayClient.ListGateway(context, req, reqOpt...)
}
