// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package isuite

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	ir "github.com/telecom-cloud/telecomcloud-sdk-go/service/isuite/ir"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type IntelligentRouterClient interface {
	CreateIntelligentRouter(context context.Context, req *ir.CreateIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.CreateIntelligentRouterResponse, rawResponse *protocol.Response, err error)

	DeleteIntelligentRouter(context context.Context, req *ir.DeleteIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.DeleteIntelligentRouterResponse, rawResponse *protocol.Response, err error)

	UpdateIntelligentRouter(context context.Context, req *ir.UpdateIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.UpdateIntelligentRouterResponse, rawResponse *protocol.Response, err error)

	OverviewIntelligentRouter(context context.Context, req *ir.OverviewIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.OverviewIntelligentRouterResponse, rawResponse *protocol.Response, err error)

	ExistIntelligentRouter(context context.Context, req *ir.ExistIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.ExistIntelligentRouterResponse, rawResponse *protocol.Response, err error)

	RedisDropdownList(context context.Context, req *ir.RedisDropdownListRequest, reqOpt ...config.RequestOption) (resp *ir.RedisDropdownListResponse, rawResponse *protocol.Response, err error)
}

type intelligentRouterClient struct {
	client *HttpClient
}

func NewIntelligentRouterClient(hostUrl string, ops ...Option) (IntelligentRouterClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &intelligentRouterClient{
		client: cli,
	}, nil
}

func (s *intelligentRouterClient) CreateIntelligentRouter(ctx context.Context, req *ir.CreateIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.CreateIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/ccse/isuite/api/v1/irs")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *intelligentRouterClient) DeleteIntelligentRouter(ctx context.Context, req *ir.DeleteIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.DeleteIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"inferenceId": req.GetInferenceId(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodDelete, "/ccse/isuite/api/v1/irs/:inferenceId")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *intelligentRouterClient) UpdateIntelligentRouter(ctx context.Context, req *ir.UpdateIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.UpdateIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"inferenceId": req.GetInferenceId(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPut, "/ccse/isuite/api/v1/irs/:inferenceId")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *intelligentRouterClient) OverviewIntelligentRouter(ctx context.Context, req *ir.OverviewIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.OverviewIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"inferenceId": req.GetInferenceId(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/ccse/isuite/api/v1/irs/:inferenceId")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *intelligentRouterClient) ExistIntelligentRouter(ctx context.Context, req *ir.ExistIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.ExistIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetPathParams(map[string]string{
			"inferenceId": req.GetInferenceId(),
		}).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/ccse/isuite/api/v1/irs/:inferenceId/exist")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *intelligentRouterClient) RedisDropdownList(ctx context.Context, req *ir.RedisDropdownListRequest, reqOpt ...config.RequestOption) (resp *ir.RedisDropdownListResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"clusterId": req.GetClusterId(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/ccse/isuite/api/v1/droplist/redis")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultIntelligentRouterClient, _ = NewIntelligentRouterClient(baseDomain)

func ConfigDefaultIntelligentRouterClient(ops ...Option) (err error) {
	defaultIntelligentRouterClient, err = NewIntelligentRouterClient(baseDomain, ops...)
	return
}

func CreateIntelligentRouter(context context.Context, req *ir.CreateIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.CreateIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	return defaultIntelligentRouterClient.CreateIntelligentRouter(context, req, reqOpt...)
}

func DeleteIntelligentRouter(context context.Context, req *ir.DeleteIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.DeleteIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	return defaultIntelligentRouterClient.DeleteIntelligentRouter(context, req, reqOpt...)
}

func UpdateIntelligentRouter(context context.Context, req *ir.UpdateIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.UpdateIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	return defaultIntelligentRouterClient.UpdateIntelligentRouter(context, req, reqOpt...)
}

func OverviewIntelligentRouter(context context.Context, req *ir.OverviewIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.OverviewIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	return defaultIntelligentRouterClient.OverviewIntelligentRouter(context, req, reqOpt...)
}

func ExistIntelligentRouter(context context.Context, req *ir.ExistIntelligentRouterRequest, reqOpt ...config.RequestOption) (resp *ir.ExistIntelligentRouterResponse, rawResponse *protocol.Response, err error) {
	return defaultIntelligentRouterClient.ExistIntelligentRouter(context, req, reqOpt...)
}

func RedisDropdownList(context context.Context, req *ir.RedisDropdownListRequest, reqOpt ...config.RequestOption) (resp *ir.RedisDropdownListResponse, rawResponse *protocol.Response, err error) {
	return defaultIntelligentRouterClient.RedisDropdownList(context, req, reqOpt...)
}
