// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package isuite

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	overview "github.com/telecom-cloud/telecomcloud-sdk-go/service/isuite/overview"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type OverviewClient interface {
	ListClusterNamespace(context context.Context, req *overview.ListClusterNamespaceRequest, reqOpt ...config.RequestOption) (resp *overview.ListClusterNamespaceResponse, rawResponse *protocol.Response, err error)
}

type overviewClient struct {
	client *HttpClient
}

func NewOverviewClient(hostUrl string, ops ...Option) (OverviewClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &overviewClient{
		client: cli,
	}, nil
}

func (s *overviewClient) ListClusterNamespace(ctx context.Context, req *overview.ListClusterNamespaceRequest, reqOpt ...config.RequestOption) (resp *overview.ListClusterNamespaceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"clusterId": req.GetClusterId(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/ccse/isuite/api/v1/namespaces")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultOverviewClient, _ = NewOverviewClient(baseDomain)

func ConfigDefaultOverviewClient(ops ...Option) (err error) {
	defaultOverviewClient, err = NewOverviewClient(baseDomain, ops...)
	return
}

func ListClusterNamespace(context context.Context, req *overview.ListClusterNamespaceRequest, reqOpt ...config.RequestOption) (resp *overview.ListClusterNamespaceResponse, rawResponse *protocol.Response, err error) {
	return defaultOverviewClient.ListClusterNamespace(context, req, reqOpt...)
}
