// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package cceone

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	cluster "github.com/telecom-cloud/telecomcloud-sdk-go/service/cceone/types/cluster"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type ClusterClient interface {
	ListClustersPage(context context.Context, req *cluster.ListClustersPageRequest, reqOpt ...config.RequestOption) (resp *cluster.ListClustersPageResponse, rawResponse *protocol.Response, err error)
}

type clusterClient struct {
	client *HttpClient
}

func NewClusterClient(hostUrl string, ops ...Option) (ClusterClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &clusterClient{
		client: cli,
	}, nil
}

func (s *clusterClient) ListClustersPage(ctx context.Context, req *cluster.ListClustersPageRequest, reqOpt ...config.RequestOption) (resp *cluster.ListClustersPageResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"pageNow":           req.GetPageNow(),
		"pageSize":          req.GetPageSize(),
		"clusterName":       req.GetClusterName(),
		"displayAllResPool": req.GetDisplayAllResPool(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/clusters/page")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultClusterClient, _ = NewClusterClient(baseDomain)

func ConfigDefaultClusterClient(ops ...Option) (err error) {
	defaultClusterClient, err = NewClusterClient(baseDomain, ops...)
	return
}

func ListClustersPage(context context.Context, req *cluster.ListClustersPageRequest, reqOpt ...config.RequestOption) (resp *cluster.ListClustersPageResponse, rawResponse *protocol.Response, err error) {
	return defaultClusterClient.ListClustersPage(context, req, reqOpt...)
}
