// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package elb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	elb "github.com/telecom-cloud/telecomcloud-sdk-go/service/elb/types/elb"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type ElbClient interface {
	CreateElbAcl(context context.Context, req *elb.CreateElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.CreateElbACLResponse, rawResponse *protocol.Response, err error)

	GetElbAcl(context context.Context, req *elb.GetElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.GetElbACLResponse, rawResponse *protocol.Response, err error)

	ListElbAcl(context context.Context, req *elb.ListElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.ListElbACLResponse, rawResponse *protocol.Response, err error)

	ListElbListener(context context.Context, req *elb.ListElbListenerRequest, reqOpt ...config.RequestOption) (resp *elb.ListElbListenerResponse, rawResponse *protocol.Response, err error)
}

type elbClient struct {
	client *HttpClient
}

func NewElbClient(hostUrl string, ops ...Option) (ElbClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &elbClient{
		client: cli,
	}, nil
}

func (s *elbClient) CreateElbAcl(ctx context.Context, req *elb.CreateElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.CreateElbACLResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v4/elb/create-access-control")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *elbClient) GetElbAcl(ctx context.Context, req *elb.GetElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.GetElbACLResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"regionID":        req.GetRegionID(),
		"id":              req.GetId(),
		"accessControlID": req.GetAccessControlID(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v4/elb/show-access-control")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *elbClient) ListElbAcl(ctx context.Context, req *elb.ListElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.ListElbACLResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"regionID": req.GetRegionID(),
		"IDs":      req.GetIDs(),
		"name":     req.GetName(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v4/elb/list-access-control")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *elbClient) ListElbListener(ctx context.Context, req *elb.ListElbListenerRequest, reqOpt ...config.RequestOption) (resp *elb.ListElbListenerResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"regionID":        req.GetRegionID(),
		"clientToken":     req.GetClientToken(),
		"projectID":       req.GetProjectID(),
		"IDs":             req.GetIDs(),
		"name":            req.GetName(),
		"loadBalancerID":  req.GetLoadBalancerID(),
		"accessControlID": req.GetAccessControlID(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionID": req.GetRegionID(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v4/elb/list-listener")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultElbClient, _ = NewElbClient(baseDomain)

func ConfigDefaultElbClient(ops ...Option) (err error) {
	defaultElbClient, err = NewElbClient(baseDomain, ops...)
	return
}

func CreateElbAcl(context context.Context, req *elb.CreateElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.CreateElbACLResponse, rawResponse *protocol.Response, err error) {
	return defaultElbClient.CreateElbAcl(context, req, reqOpt...)
}

func GetElbAcl(context context.Context, req *elb.GetElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.GetElbACLResponse, rawResponse *protocol.Response, err error) {
	return defaultElbClient.GetElbAcl(context, req, reqOpt...)
}

func ListElbAcl(context context.Context, req *elb.ListElbACLRequest, reqOpt ...config.RequestOption) (resp *elb.ListElbACLResponse, rawResponse *protocol.Response, err error) {
	return defaultElbClient.ListElbAcl(context, req, reqOpt...)
}

func ListElbListener(context context.Context, req *elb.ListElbListenerRequest, reqOpt ...config.RequestOption) (resp *elb.ListElbListenerResponse, rawResponse *protocol.Response, err error) {
	return defaultElbClient.ListElbListener(context, req, reqOpt...)
}
