// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package aigw

import (
	"crypto/tls"

	cli "github.com/telecom-cloud/client-go/pkg/client"
)

var baseDomain = "https://agw-global.ctapi.ctyun.cn"

type ClientSet interface {
	ModelApi() ModelApiClient
	GatewayInstance() GatewayInstanceClient
	Upstream() UpstreamClient
	UpstreamSource() UpstreamSourceClient
}

type clientSet struct {
	modelApiCli        ModelApiClient
	gatewayInstanceCli GatewayInstanceClient
	upstreamCli        UpstreamClient
	upstreamSourceCli  UpstreamSourceClient
}

func NewClientSet(baseDomain string, options ...Option) (ClientSet, error) {
	defaultOpt := []Option{
		WithClientOption(cli.WithTLSConfig(&tls.Config{
			InsecureSkipVerify: true,
		})),
	}
	options = append(defaultOpt, options...)
	modelApiCli, err := NewModelApiClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}
	gatewayInstanceCli, err := NewGatewayInstanceClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}
	upstreamCli, err := NewUpstreamClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}
	upstreamSourceCli, err := NewUpstreamSourceClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}

	return &clientSet{
		modelApiCli:        modelApiCli,
		gatewayInstanceCli: gatewayInstanceCli,
		upstreamCli:        upstreamCli,
		upstreamSourceCli:  upstreamSourceCli,
	}, nil
}

func (cs *clientSet) ModelApi() ModelApiClient {
	return cs.modelApiCli
}

func (cs *clientSet) GatewayInstance() GatewayInstanceClient {
	return cs.gatewayInstanceCli
}

func (cs *clientSet) Upstream() UpstreamClient {
	return cs.upstreamCli
}

func (cs *clientSet) UpstreamSource() UpstreamSourceClient {
	return cs.upstreamSourceCli
}
