// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package aigw

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	gatewayinstance "github.com/telecom-cloud/telecomcloud-sdk-go/service/aigw/types/gatewayinstance"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type GatewayInstanceClient interface {
	GetExposedAddress(context context.Context, req *gatewayinstance.GetExposedAddressRequest, reqOpt ...config.RequestOption) (resp *gatewayinstance.GetExposedAddressResponse, rawResponse *protocol.Response, err error)

	ListGatewayInstance(context context.Context, req *gatewayinstance.ListBaseInfoRequest, reqOpt ...config.RequestOption) (resp *gatewayinstance.ListBaseInfoResponse, rawResponse *protocol.Response, err error)
}

type gatewayInstanceClient struct {
	client *HttpClient
}

func NewGatewayInstanceClient(hostUrl string, ops ...Option) (GatewayInstanceClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &gatewayInstanceClient{
		client: cli,
	}, nil
}

func (s *gatewayInstanceClient) GetExposedAddress(ctx context.Context, req *gatewayinstance.GetExposedAddressRequest, reqOpt ...config.RequestOption) (resp *gatewayinstance.GetExposedAddressResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"instanceCode": req.GetInstanceCode(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/instance/exposed-address")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *gatewayInstanceClient) ListGatewayInstance(ctx context.Context, req *gatewayinstance.ListBaseInfoRequest, reqOpt ...config.RequestOption) (resp *gatewayinstance.ListBaseInfoResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"gatewayType": req.GetGatewayType(),
		"bizState":    req.GetBizState(),
		"vpcUuid":     req.GetVpcId(),
		"regionCode":  req.GetRegionCode(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/instance/list-base-info")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultGatewayInstanceClient, _ = NewGatewayInstanceClient(baseDomain)

func ConfigDefaultGatewayInstanceClient(ops ...Option) (err error) {
	defaultGatewayInstanceClient, err = NewGatewayInstanceClient(baseDomain, ops...)
	return
}

func GetExposedAddress(context context.Context, req *gatewayinstance.GetExposedAddressRequest, reqOpt ...config.RequestOption) (resp *gatewayinstance.GetExposedAddressResponse, rawResponse *protocol.Response, err error) {
	return defaultGatewayInstanceClient.GetExposedAddress(context, req, reqOpt...)
}

func ListGatewayInstance(context context.Context, req *gatewayinstance.ListBaseInfoRequest, reqOpt ...config.RequestOption) (resp *gatewayinstance.ListBaseInfoResponse, rawResponse *protocol.Response, err error) {
	return defaultGatewayInstanceClient.ListGatewayInstance(context, req, reqOpt...)
}
