// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package aigw

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	modelapi "github.com/telecom-cloud/telecomcloud-sdk-go/service/aigw/types/modelapi"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type ModelApiClient interface {
	CreateModelApi(context context.Context, req *modelapi.CreateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.CreateModelApiResponse, rawResponse *protocol.Response, err error)

	PreCheckModelApi(context context.Context, req *modelapi.CreateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.CreateModelApiResponse, rawResponse *protocol.Response, err error)

	UpdateModelApi(context context.Context, req *modelapi.UpdateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.UpdateModelApiResponse, rawResponse *protocol.Response, err error)

	DeleteModelApi(context context.Context, req *modelapi.DeleteModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.DeleteModelApiResponse, rawResponse *protocol.Response, err error)

	ListModelApi(context context.Context, req *modelapi.ListModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.ListModelApiResponse, rawResponse *protocol.Response, err error)

	ListModelApiRoute(context context.Context, req *modelapi.ListModelApiRouteRequest, reqOpt ...config.RequestOption) (resp *modelapi.ListModelApiRouteResponse, rawResponse *protocol.Response, err error)

	GetRouteNames(context context.Context, req *modelapi.GetRouteNamesRequest, reqOpt ...config.RequestOption) (resp *modelapi.GetRouteNamesResponse, rawResponse *protocol.Response, err error)
}

type modelApiClient struct {
	client *HttpClient
}

func NewModelApiClient(hostUrl string, ops ...Option) (ModelApiClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &modelApiClient{
		client: cli,
	}, nil
}

func (s *modelApiClient) CreateModelApi(ctx context.Context, req *modelapi.CreateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.CreateModelApiResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/model/api/create")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *modelApiClient) PreCheckModelApi(ctx context.Context, req *modelapi.CreateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.CreateModelApiResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/model/api/create/pre-check")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *modelApiClient) UpdateModelApi(ctx context.Context, req *modelapi.UpdateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.UpdateModelApiResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPut, "/v1/model/api/update")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *modelApiClient) DeleteModelApi(ctx context.Context, req *modelapi.DeleteModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.DeleteModelApiResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodDelete, "/v1/model/api/delete")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *modelApiClient) ListModelApi(ctx context.Context, req *modelapi.ListModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.ListModelApiResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"pageNum":      req.GetPageNum(),
		"pageSize":     req.GetPageSize(),
		"instanceCode": req.GetInstanceCode(),
		"name":         req.GetName(),
		"subType":      req.GetSubType(),
		"consumerCode": req.GetConsumerCode(),
		"upstreamCode": req.GetUpstreamCode(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/model/api/all-for-isuite")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *modelApiClient) ListModelApiRoute(ctx context.Context, req *modelapi.ListModelApiRouteRequest, reqOpt ...config.RequestOption) (resp *modelapi.ListModelApiRouteResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"apiCode":   req.GetApiCode(),
		"routeName": req.GetRouteName(),
		"path":      req.GetPath(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/model/api/route-list")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *modelApiClient) GetRouteNames(ctx context.Context, req *modelapi.GetRouteNamesRequest, reqOpt ...config.RequestOption) (resp *modelapi.GetRouteNamesResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"subType":     req.GetSubType(),
		"llmProtocol": req.GetLlmProtocol(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/model/api/list-route-name")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultModelApiClient, _ = NewModelApiClient(baseDomain)

func ConfigDefaultModelApiClient(ops ...Option) (err error) {
	defaultModelApiClient, err = NewModelApiClient(baseDomain, ops...)
	return
}

func CreateModelApi(context context.Context, req *modelapi.CreateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.CreateModelApiResponse, rawResponse *protocol.Response, err error) {
	return defaultModelApiClient.CreateModelApi(context, req, reqOpt...)
}

func PreCheckModelApi(context context.Context, req *modelapi.CreateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.CreateModelApiResponse, rawResponse *protocol.Response, err error) {
	return defaultModelApiClient.PreCheckModelApi(context, req, reqOpt...)
}

func UpdateModelApi(context context.Context, req *modelapi.UpdateModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.UpdateModelApiResponse, rawResponse *protocol.Response, err error) {
	return defaultModelApiClient.UpdateModelApi(context, req, reqOpt...)
}

func DeleteModelApi(context context.Context, req *modelapi.DeleteModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.DeleteModelApiResponse, rawResponse *protocol.Response, err error) {
	return defaultModelApiClient.DeleteModelApi(context, req, reqOpt...)
}

func ListModelApi(context context.Context, req *modelapi.ListModelApiRequest, reqOpt ...config.RequestOption) (resp *modelapi.ListModelApiResponse, rawResponse *protocol.Response, err error) {
	return defaultModelApiClient.ListModelApi(context, req, reqOpt...)
}

func ListModelApiRoute(context context.Context, req *modelapi.ListModelApiRouteRequest, reqOpt ...config.RequestOption) (resp *modelapi.ListModelApiRouteResponse, rawResponse *protocol.Response, err error) {
	return defaultModelApiClient.ListModelApiRoute(context, req, reqOpt...)
}

func GetRouteNames(context context.Context, req *modelapi.GetRouteNamesRequest, reqOpt ...config.RequestOption) (resp *modelapi.GetRouteNamesResponse, rawResponse *protocol.Response, err error) {
	return defaultModelApiClient.GetRouteNames(context, req, reqOpt...)
}
