// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package aigw

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	upstream "github.com/telecom-cloud/telecomcloud-sdk-go/service/aigw/types/upstream"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type UpstreamClient interface {
	CreateISuiteUpstream(context context.Context, req *upstream.CreateISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.CreateISuiteUpstreamResponse, rawResponse *protocol.Response, err error)

	UpdateISuiteUpstream(context context.Context, req *upstream.UpdateISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.UpdateISuiteUpstreamResponse, rawResponse *protocol.Response, err error)

	DeleteISuiteUpstream(context context.Context, req *upstream.DeleteISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.DeleteISuiteUpstreamResponse, rawResponse *protocol.Response, err error)

	GetISuiteUpstream(context context.Context, req *upstream.GetISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.GetISuiteUpstreamResponse, rawResponse *protocol.Response, err error)
}

type upstreamClient struct {
	client *HttpClient
}

func NewUpstreamClient(hostUrl string, ops ...Option) (UpstreamClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &upstreamClient{
		client: cli,
	}, nil
}

func (s *upstreamClient) CreateISuiteUpstream(ctx context.Context, req *upstream.CreateISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.CreateISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId":    req.GetRegionId(),
			"clientToken": req.GetClientToken(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/upstream/create-isuite")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *upstreamClient) UpdateISuiteUpstream(ctx context.Context, req *upstream.UpdateISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.UpdateISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId":    req.GetRegionId(),
			"clientToken": req.GetClientToken(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/upstream/update-isuite")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *upstreamClient) DeleteISuiteUpstream(ctx context.Context, req *upstream.DeleteISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.DeleteISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/upstream/delete")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *upstreamClient) GetISuiteUpstream(ctx context.Context, req *upstream.GetISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.GetISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"instanceCode":  req.GetInstanceCode(),
		"namespace":     req.GetNamespace(),
		"inferenceName": req.GetInferenceName(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/upstream/isuite/one")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultUpstreamClient, _ = NewUpstreamClient(baseDomain)

func ConfigDefaultUpstreamClient(ops ...Option) (err error) {
	defaultUpstreamClient, err = NewUpstreamClient(baseDomain, ops...)
	return
}

func CreateISuiteUpstream(context context.Context, req *upstream.CreateISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.CreateISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	return defaultUpstreamClient.CreateISuiteUpstream(context, req, reqOpt...)
}

func UpdateISuiteUpstream(context context.Context, req *upstream.UpdateISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.UpdateISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	return defaultUpstreamClient.UpdateISuiteUpstream(context, req, reqOpt...)
}

func DeleteISuiteUpstream(context context.Context, req *upstream.DeleteISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.DeleteISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	return defaultUpstreamClient.DeleteISuiteUpstream(context, req, reqOpt...)
}

func GetISuiteUpstream(context context.Context, req *upstream.GetISuiteUpstreamRequest, reqOpt ...config.RequestOption) (resp *upstream.GetISuiteUpstreamResponse, rawResponse *protocol.Response, err error) {
	return defaultUpstreamClient.GetISuiteUpstream(context, req, reqOpt...)
}
