// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package als

import (
	"crypto/tls"

	cli "github.com/telecom-cloud/client-go/pkg/client"
)

var baseDomain = "https://ctlts-global.ctapi.ctyun.cn"

type ClientSet interface {
	Project() ProjectClient
	Unit() UnitClient
	Rule() RuleClient
	Service() ServiceClient
}

type clientSet struct {
	projectCli ProjectClient
	unitCli    UnitClient
	ruleCli    RuleClient
	serviceCli ServiceClient
}

func NewClientSet(baseDomain string, options ...Option) (ClientSet, error) {
	defaultOpt := []Option{
		WithClientOption(cli.WithTLSConfig(&tls.Config{
			InsecureSkipVerify: true,
		})),
	}
	options = append(defaultOpt, options...)
	projectCli, err := NewProjectClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}
	unitCli, err := NewUnitClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}
	ruleCli, err := NewRuleClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}
	serviceCli, err := NewServiceClient(baseDomain, options...)
	if err != nil {
		return nil, err
	}

	return &clientSet{
		projectCli: projectCli,
		unitCli:    unitCli,
		ruleCli:    ruleCli,
		serviceCli: serviceCli,
	}, nil
}

func (cs *clientSet) Project() ProjectClient {
	return cs.projectCli
}

func (cs *clientSet) Unit() UnitClient {
	return cs.unitCli
}

func (cs *clientSet) Rule() RuleClient {
	return cs.ruleCli
}

func (cs *clientSet) Service() ServiceClient {
	return cs.serviceCli
}
