// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package als

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	rule "github.com/telecom-cloud/telecomcloud-sdk-go/service/als/types/rule"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type RuleClient interface {
	CreateRule(context context.Context, req *rule.CreateRuleRequest, reqOpt ...config.RequestOption) (resp *rule.CreateRuleResponse, rawResponse *protocol.Response, err error)

	DeleteRule(context context.Context, req *rule.DeleteRuleRequest, reqOpt ...config.RequestOption) (resp *rule.DeleteRuleResponse, rawResponse *protocol.Response, err error)

	GetRule(context context.Context, req *rule.GetRuleRequest, reqOpt ...config.RequestOption) (resp *rule.GetRuleResponse, rawResponse *protocol.Response, err error)

	ApplyRule(context context.Context, req *rule.RuleApplyRequest, reqOpt ...config.RequestOption) (resp *rule.RuleApplyResponse, rawResponse *protocol.Response, err error)
}

type ruleClient struct {
	client *HttpClient
}

func NewRuleClient(hostUrl string, ops ...Option) (RuleClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &ruleClient{
		client: cli,
	}, nil
}

func (s *ruleClient) CreateRule(ctx context.Context, req *rule.CreateRuleRequest, reqOpt ...config.RequestOption) (resp *rule.CreateRuleResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/collectorRule/create")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *ruleClient) DeleteRule(ctx context.Context, req *rule.DeleteRuleRequest, reqOpt ...config.RequestOption) (resp *rule.DeleteRuleResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/collectorRule/delete")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *ruleClient) GetRule(ctx context.Context, req *rule.GetRuleRequest, reqOpt ...config.RequestOption) (resp *rule.GetRuleResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"ruleName": req.GetRuleName(),
		"unitCode": req.GetUnitCode(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/collectorRule/getRuleConfigByName")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *ruleClient) ApplyRule(ctx context.Context, req *rule.RuleApplyRequest, reqOpt ...config.RequestOption) (resp *rule.RuleApplyResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/collectorRule/hostGroup/apply")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultRuleClient, _ = NewRuleClient(baseDomain)

func ConfigDefaultRuleClient(ops ...Option) (err error) {
	defaultRuleClient, err = NewRuleClient(baseDomain, ops...)
	return
}

func CreateRule(context context.Context, req *rule.CreateRuleRequest, reqOpt ...config.RequestOption) (resp *rule.CreateRuleResponse, rawResponse *protocol.Response, err error) {
	return defaultRuleClient.CreateRule(context, req, reqOpt...)
}

func DeleteRule(context context.Context, req *rule.DeleteRuleRequest, reqOpt ...config.RequestOption) (resp *rule.DeleteRuleResponse, rawResponse *protocol.Response, err error) {
	return defaultRuleClient.DeleteRule(context, req, reqOpt...)
}

func GetRule(context context.Context, req *rule.GetRuleRequest, reqOpt ...config.RequestOption) (resp *rule.GetRuleResponse, rawResponse *protocol.Response, err error) {
	return defaultRuleClient.GetRule(context, req, reqOpt...)
}

func ApplyRule(context context.Context, req *rule.RuleApplyRequest, reqOpt ...config.RequestOption) (resp *rule.RuleApplyResponse, rawResponse *protocol.Response, err error) {
	return defaultRuleClient.ApplyRule(context, req, reqOpt...)
}
