// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package als

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	service "github.com/telecom-cloud/telecomcloud-sdk-go/service/als/types/service"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type ServiceClient interface {
	CheckService(context context.Context, req *service.CheckServiceRequest, reqOpt ...config.RequestOption) (resp *service.CheckServiceResponse, rawResponse *protocol.Response, err error)

	OpenService(context context.Context, req *service.OpenServiceRequest, reqOpt ...config.RequestOption) (resp *service.OpenServiceResponse, rawResponse *protocol.Response, err error)
}

type serviceClient struct {
	client *HttpClient
}

func NewServiceClient(hostUrl string, ops ...Option) (ServiceClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &serviceClient{
		client: cli,
	}, nil
}

func (s *serviceClient) CheckService(ctx context.Context, req *service.CheckServiceRequest, reqOpt ...config.RequestOption) (resp *service.CheckServiceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/order/instance/checkLicense")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *serviceClient) OpenService(ctx context.Context, req *service.OpenServiceRequest, reqOpt ...config.RequestOption) (resp *service.OpenServiceResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/order/instance/open")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultServiceClient, _ = NewServiceClient(baseDomain)

func ConfigDefaultServiceClient(ops ...Option) (err error) {
	defaultServiceClient, err = NewServiceClient(baseDomain, ops...)
	return
}

func CheckService(context context.Context, req *service.CheckServiceRequest, reqOpt ...config.RequestOption) (resp *service.CheckServiceResponse, rawResponse *protocol.Response, err error) {
	return defaultServiceClient.CheckService(context, req, reqOpt...)
}

func OpenService(context context.Context, req *service.OpenServiceRequest, reqOpt ...config.RequestOption) (resp *service.OpenServiceResponse, rawResponse *protocol.Response, err error) {
	return defaultServiceClient.OpenService(context, req, reqOpt...)
}
