// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package als

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	unit "github.com/telecom-cloud/telecomcloud-sdk-go/service/als/types/unit"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type UnitClient interface {
	CreateUnit(context context.Context, req *unit.CreateUnitRequest, reqOpt ...config.RequestOption) (resp *unit.CreateUnitResponse, rawResponse *protocol.Response, err error)

	DeleteUnit(context context.Context, req *unit.DeleteUnitRequest, reqOpt ...config.RequestOption) (resp *unit.DeleteUnitResponse, rawResponse *protocol.Response, err error)

	ListUnit(context context.Context, req *unit.ListUnitRequest, reqOpt ...config.RequestOption) (resp *unit.ListUnitResponse, rawResponse *protocol.Response, err error)
}

type unitClient struct {
	client *HttpClient
}

func NewUnitClient(hostUrl string, ops ...Option) (UnitClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &unitClient{
		client: cli,
	}, nil
}

func (s *unitClient) CreateUnit(ctx context.Context, req *unit.CreateUnitRequest, reqOpt ...config.RequestOption) (resp *unit.CreateUnitResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/unit/create")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *unitClient) DeleteUnit(ctx context.Context, req *unit.DeleteUnitRequest, reqOpt ...config.RequestOption) (resp *unit.DeleteUnitResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/unit/delete")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

func (s *unitClient) ListUnit(ctx context.Context, req *unit.ListUnitRequest, reqOpt ...config.RequestOption) (resp *unit.ListUnitResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	queryParams := map[string]interface{}{
		"projectCode": req.GetProjectCode(),
		"unitName":    req.GetUnitName(),
	}
	OptimizeQueryParams(queryParams)
	ret, err := s.client.R().
		SetContext(ctx).
		SetQueryParams(queryParams).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodGet, "/v1/unit/list")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultUnitClient, _ = NewUnitClient(baseDomain)

func ConfigDefaultUnitClient(ops ...Option) (err error) {
	defaultUnitClient, err = NewUnitClient(baseDomain, ops...)
	return
}

func CreateUnit(context context.Context, req *unit.CreateUnitRequest, reqOpt ...config.RequestOption) (resp *unit.CreateUnitResponse, rawResponse *protocol.Response, err error) {
	return defaultUnitClient.CreateUnit(context, req, reqOpt...)
}

func DeleteUnit(context context.Context, req *unit.DeleteUnitRequest, reqOpt ...config.RequestOption) (resp *unit.DeleteUnitResponse, rawResponse *protocol.Response, err error) {
	return defaultUnitClient.DeleteUnit(context, req, reqOpt...)
}

func ListUnit(context context.Context, req *unit.ListUnitRequest, reqOpt ...config.RequestOption) (resp *unit.ListUnitResponse, rawResponse *protocol.Response, err error) {
	return defaultUnitClient.ListUnit(context, req, reqOpt...)
}
