// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Telecom Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package als

import (
	"context"
	"fmt"
	"net/http"

	"github.com/telecom-cloud/client-go/pkg/common/config"
	"github.com/telecom-cloud/client-go/pkg/openapi"
	"github.com/telecom-cloud/client-go/pkg/protocol"

	vpce "github.com/telecom-cloud/telecomcloud-sdk-go/service/als/types/vpce"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type VPCEClient interface {
	CreateVPCE(context context.Context, req *vpce.CreateVPCERequest, reqOpt ...config.RequestOption) (resp *vpce.CreateVPCEResponse, rawResponse *protocol.Response, err error)
}

type vPCEClient struct {
	client *HttpClient
}

func NewVPCEClient(hostUrl string, ops ...Option) (VPCEClient, error) {
	opts := GetOptions(append(ops, WithHostUrl(hostUrl))...)
	cli, err := NewHttpClient(opts)
	if err != nil {
		return nil, err
	}
	return &vPCEClient{
		client: cli,
	}, nil
}

func (s *vPCEClient) CreateVPCE(ctx context.Context, req *vpce.CreateVPCERequest, reqOpt ...config.RequestOption) (resp *vpce.CreateVPCEResponse, rawResponse *protocol.Response, err error) {
	openapiResp := &openapi.Response{}
	openapiResp.ReturnObj = &resp

	ret, err := s.client.R().
		SetContext(ctx).
		AddHeaders(map[string]string{
			"regionId": req.GetRegionId(),
		}).
		SetBodyParam(req).
		SetRequestOption(reqOpt...).
		SetResult(openapiResp).
		Execute(http.MethodPost, "/v1/delegate/createVpce")
	if err != nil {
		return nil, nil, err
	}

	rawResponse = ret.RawResponse
	return resp, rawResponse, nil
}

var defaultVPCEClient, _ = NewVPCEClient(baseDomain)

func ConfigDefaultVPCEClient(ops ...Option) (err error) {
	defaultVPCEClient, err = NewVPCEClient(baseDomain, ops...)
	return
}

func CreateVPCE(context context.Context, req *vpce.CreateVPCERequest, reqOpt ...config.RequestOption) (resp *vpce.CreateVPCEResponse, rawResponse *protocol.Response, err error) {
	return defaultVPCEClient.CreateVPCE(context, req, reqOpt...)
}
